// users
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Name1",
    "lastName": "LastName1",
    "dob": "12.02.2023",
    "email": "email@email.com",
    "password":"123",
    "height": "200",
    "weight": "70",
    "role": "Coach"
}

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "email@email.com",
    "password":"123"
}

//plans
POST http://localhost:3000/plans
Content-Type: application/json

{
    "title": "Plan54",
    "description": "Plan2 desc",
    "startDate": "2023-02-12T15:39:06.875Z",
    "endDate": "2023-02-20T15:39:06.875Z",
    "userId": "1"

}

GET http://localhost:3000/plans
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik5hbWUxIiwibGFzdE5hbWUiOiJMYXN0TmFtZTEiLCJkb2IiOiIyMDIzLTEyLTAxVDIzOjAwOjAwLjAwMFoiLCJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzIiwiaGVpZ2h0IjoyMDAsIndlaWdodCI6NzAsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTY1NzY1Mn0.Y5WC51Omuzz_z6L_lYHuJ2ADg1_mqXRFnerG9e7U2CM

DELETE http://localhost:3000/plans
Content-Type: application/json

{
    "id": "2"
} 

//reviews
POST http://localhost:3000/reviews
Content-Type: application/json

{
    "comment": "Comment 5",
    "rating": "3",
    "planId": "3"
}

GET http://localhost:3000/reviews/coach
Content-Type: application/json

{
    "id" : "1"
}

GET http://localhost:3000/plans/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik5hbWUxIiwibGFzdE5hbWUiOiJMYXN0TmFtZTEiLCJkb2IiOiIyMDIzLTEyLTAxVDIzOjAwOjAwLjAwMFoiLCJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzIiwiaGVpZ2h0IjoyMDAsIndlaWdodCI6NzAsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTY1NzY1Mn0.Y5WC51Omuzz_z6L_lYHuJ2ADg1_mqXRFnerG9e7U2CM

